[package]
name = "wryebot"
version = "0.1.0"
authors = ["Infernio <infernio@icloud.com>"]
edition = "2018"
description = "A bot for the Wrye Bash project."
repository = "https://github.com/Infernio/wryebot"
license = "GPL-3.0-or-later"

[dependencies]
