name: CI

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-ver: [3.9, 3.10-dev]
    runs-on: '${{ matrix.os }}'
    name: 'Python ${{ matrix.python-ver }} on ${{ matrix.os }}'
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: 'Set up Python ${{ matrix.python-ver }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-ver }}'
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
      - name: Lint with pylint
        run: |
          python -m pylint src
