name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Install Rust Stable
        run: rustup update --no-self-update stable && rustup default stable

      - name: Check with rustfmt
        run: cargo fmt -- --check

      - name: Check with clippy
        run: cargo clippy

  test:
    name: Testing
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        channel: [stable, beta, nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Install Rust ${{ matrix.channel }}
        run: rustup update --no-self-update $CHANNEL && rustup default $CHANNEL
        env:
          CHANNEL: ${{ matrix.channel }}

      - name: Build wryebot
        run: cargo build

      - name: Test wryebot
        run: cargo test
